# Generated by Django 4.1.6 on 2023-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
